### ISSUE TITLE
update/reduce/remove 'level' concept after parenting PR

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/ebml-specification#104]
Just a note to review all language about 'levels' after the https://github.com/Matroska-Org/ebml-specification/pull/83 is accepted. See in particular https://github.com/Matroska-Org/ebml-specification/pull/103#discussion_r80261595.

**Comment by robUx4** [comment]
Is this still relevant? After the ba883577176722bbddcc9e7c0594e9d6820a4214 merge it seems `Level` is used for element naming and `level` is used in the text body. Do we need to define what's an element level ?

**Comment by robUx4** [comment]
cc @retokromer

**Comment by retokromer** [comment]
@robUx4 On my side, this one can be closed.
