### ISSUE TITLE
Use an enumeration the EBML Schema rather than list values in text

### ISSUE THREAD

**Issue by robUx4** [Matroska-Org/ebml-specification#114]
Something of this kind:
`<enum value="1">
  <documentation language="en">Rectangular</documentation>
</enum>`

**Comment by dericed** [comment]
Perhaps it the enum should allow:
- value: the stored value
- name: a concise, human readable label for the value
- documentation (with lang attribute): to further describe the value
- constraint: Human-readable information about how the use of the value adds constraints to the rest of the document.

For instance the enumeration structure should be able to fit logic such as described at https://github.com/google/spatial-media/blob/master/docs/spherical-video-v2-rfc.md#projectionprivate-element.

**Comment by ablwr** [comment]
Hmm... do you anticipate it nesting like this...?

```
<element name="FlagInterlaced" path="1*1(\Segment\Tracks\TrackEntry\Video\FlagInterlaced)" cppname="VideoFlagInterlaced" id="0x9A" type="uinteger" minOccurs="1" minver="2" webm="1" default="0" range="0-2">
    <documentation lang="en">A flag to declare is the video is known to be progressive or interlaced and if applicable to declare details about the interlacement.</documentation>
    <enum value="0"><documentation lang="en">undetermined</documentation></enum>
    <enum value="1"><documentation lang="en">interlaced</documentation></enum>
    <enum value="2"><documentation lang="en">progressive</documentation></enum>
</element>
```

**Comment by dericed** [comment]
That looks good to me. On the documentation part of the enum, I think in some of the docs from Google there is a distinction between the label of the value and the semantic meaning. For instance see the proposed [ProjectionPrivate Element](https://github.com/google/spatial-media/blob/master/docs/spherical-video-v2-rfc.md#projectionprivate-element). Here for each enum it breaks down to perhaps three values:

- value = 2
- label = Cubemap
- semantics = ... then this element must be present and contain the same binary data that would be stored inside an ISOBMFF Cubemap Projection Box ('cbmp').

Perhaps (not sure if I'm conveying the semantics properly):

```
<enum value="2" label="Cubemap">
   <documentation lang="en">this element must be present and contain the same binary data that would be stored inside an ISOBMFF Cubemap Projection Box ('cbmp').</documentation>
</enum>
```

cc @dcower @kodabb @acolwell

**Comment by acolwell** [comment]
Yes. The ProjectionPrivate field is intended to act similar to the CodecPrivate field. The contents of the field are dependent on the value in the enum field. If I understand this proposal correctly, for the ProjectionType enum I'd expect the <documentation> inside the <enum> to describe the specific projection and the <constraint> or <semantics> to indicate that a ProjectionPrivate element must be present and what it should contain. I then would expect the ProjectionPrivate <semantics> to indicate that ProjectionType must be present and the contents of this element must conform to the semantics provided in the ProjectionType enum value semantics.

I think this is what you are proposing. Let me know if I've misunderstood something. ISTM that the enum values should really own the semantics and dependent elements like ProjectionPrivate should just defer to the info in enum value description.

**Comment by dericed** [comment]
Hi @acolwell I don't exactly understand your sentence `If I understand this proposal correctly, for the ProjectionType enum I'd expect the inside the to describe the specific projection and the or to indicate that a ProjectionPrivate element must be present and what it should contain.`

But I think I misunderstood in what I was writing above about `ProjectionPrivate` since that field itself doesn't have a enumation list but it's content is contextually dependent on a related value. I'm not sure if these should be defined in a machine-readable way in the EBML Schema for Matroska or not.

Maybe this would be better expressed like (adding a context attribute):
```xml
<element name="ProjectionPrivate">
  <documentation lang="en" context="./ProjectionType='0'">this element must not be present</documentation>
  <documentation lang="en" context="./ProjectionType='1'">then this element must be present and contain the same binary data that would be stored inside an ISOBMFF Equirectangular Projection Box ('equi')</documentation>
  <documentation lang="en" context="./ProjectionType='2'">this element must be present and contain the same binary data that would be stored inside an ISOBMFF Cubemap Projection Box ('cbmp').</documentation>
  <documentation lang="en" context="./ProjectionType='3'">this element must be present and contain the same binary data that would be stored inside an ISOBMFF Mesh Projection Box ('mshp')</documentation>
</element>
```

**Comment by acolwell** [comment]
Hi @dericed .  It looks like the tag names got stripped from what I originally wrote for some reason.  Sorry to sound like a crazy person. :)  Lets try that again.

If I understand this proposal correctly, for the ProjectionType enum I'd expect the "documentation tag" inside the "enum tag" to describe the specific projection and the "constriant tag" or "semantics tag" to indicate that a ProjectionPrivate element must be present and what it should contain.  I then would expect the ProjectionPrivate "semantics tag" to indicate that ProjectionType must be present and the contents of this element must conform to the semantics provided in the ProjectionType enum value semantics.

Hopefully that makes more sense. Your more recent proposal also looks fine to me.

**Comment by dericed** [comment]
Here's an update draft for the two elements with the enumeration structure:

```xml
<element name="ProjectionType" path="1*1(\Segment\Tracks\TrackEntry\Video\ProjectionType)" id="0x7671" type="uinteger" minOccurs="1" minver="4" default="0" range="0-3" webm="1">
  <documentation lang="en">Describes the projection used for this video track.</documentation>
  <enum value="0" label="Rectangular" />
  <enum value="1" label="Equirectangular" />
  <enum value="2" label="Cubemap" />
  <enum value="3" label="Mesh" />
</element>
<element name="ProjectionPrivate" path="0*1(\Segment\Tracks\TrackEntry\Video\ProjectionPrivate)" id="0x7672" type="binary" minver="4" webm="1">
  <documentation lang="en">Private data that only applies to a specific projection. Note: ISOBMFF box size and fourcc fields are not included in the binary data, but the FullBox version and flag fields are. This is to avoid redundant framing information while preserving versioning and semantics between the two container formats.</documentation>
  <documentation lang="en" context="./ProjectionType='0'">this element must not be present</documentation>
  <documentation lang="en" context="./ProjectionType='1'">then this element must be present and contain the same binary data that would be stored inside an ISOBMFF Equirectangular Projection Box ('equi')</documentation>
  <documentation lang="en" context="./ProjectionType='2'">this element must be present and contain the same binary data that would be stored inside an ISOBMFF Cubemap Projection Box ('cbmp').</documentation>
  <documentation lang="en" context="./ProjectionType='3'">this element must be present and contain the same binary data that would be stored inside an ISOBMFF Mesh Projection Box ('mshp')</documentation>
</element>
```

Some remaining issues with this:
- Should the `<enum>` values be contained within something?
- The `<documentation> ` in `ProjectionPrivate` seems to mix two types, should we distinction the names of these to separate overall Element documentation from contextual documentation?

**Comment by dericed** [comment]
Also noting that the `context` values use an xpath-like address to the related `ProjectionType` but this type of expression also needs to be defined in EBML.

**Comment by dericed** [comment]
see https://github.com/Matroska-Org/matroska-specification/pull/92 and https://github.com/Matroska-Org/ebml-specification/pull/130

**Comment by dericed** [comment]
closing. I think this is complete.
