### ISSUE TITLE
what should maxOccurs= if 'unbounded'

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/ebml-specification#116]
In the new definition of [maxOccurs](https://github.com/Matroska-Org/ebml-specification/blob/master/specification.markdown#maxoccurs), it's unclear what to say if the maximum occurrence is unbounded. Before we had `maxOccurs='unbounded'`, what now?

**Comment by robUx4** [comment]
See https://github.com/Matroska-Org/ebml-specification/pull/124

**Comment by dericed** [comment]
Resolved in https://github.com/Matroska-Org/ebml-specification/pull/124
