### ISSUE TITLE
Ordering of Notation and Conventions

### ISSUE THREAD

**Issue by bastik-tor** [Matroska-Org/ebml-specification#120]
This section from specification.markdown does not appear to define its terms in a structure that is related to the format or in a logical fashion that follows from the format. Instead it appears to be ordered alphabetically, but not fully.

Is that intentional?

**Comment by dericed** [comment]
I think I originally wrote it as alphabetical, although since writing it this way I've seen other RFCs use a more structural order rather than alphabetical.

**Comment by bastik-tor** [comment]
This issue is mainly to ask if that is something that MUST be changed (it has to alphabetical) or if the order SHOULD change to something else or if it MAY be in any way one would see fit.

If it is something that can stay the way it is, this issue can be closed, unless someone sees a requirement for a change.

**Comment by dericed** [comment]
AFAICT there is no MUST but IETF protocols MAY offer some guidance here, thus the question is better put on CELLAR than here.

**Comment by dericed** [comment]
I think the order could be redone, so that definitions are not forward-referencing other definitions. For instance `Element Data` refers to `Element ID` in its definition but is before it. I have two other open PRs in this section, so can do the reordering after those to avoid conflicts.
