### ISSUE TITLE
how to constrain EBML Header with an EBML Schema

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/ebml-specification#128]
This issue is based on an initial discussion at https://github.com/Matroska-Org/ebml-specification/issues/98#issuecomment-249088418.

The `EBML Schema` section claims:

> The `EBML Schema` does not itself document the `EBML Header`, but documents all data of the `EBML Document` that follows the `EBML Header`. The `EBML Header` itself is documented by this specification in the `EBML Header Elements` (see [EBML Header Elements](#ebml-header-elements)). The `EBML Schema` also does not document `Global Elements` that are defined by this document (namely the `Void Element` and the `CRC-32 Element`).

However we have cases where EBML Document Types (Matroska) add additional constraints to the EBML Header. For example, EBML allows EBMLMaxSizeLength=9 but Matroska doesn't.

Should we change the above noted paragraph to say:

> The `EBML Schema` MUST begin with a definition of the `EBML Header` and EBML's `Global Elements` which is followed with a definition of the `EBML Body`. The `EBML Schema` MUST document the ` of the `EBML Header` as documented by this specification in the `EBML Header Elements` (see [EBML Header Elements](#ebml-header-elements)), but MAY constrain those `Elements` by adding or constraining the `range` attributes. For example, an `EBML Schema` MAY constrain the `EBMLMaxSizeLength` to a maximum value of `8`.

The example schema would then need to be updated to include the Header and Global Elements. The downside is that this causes some redundancy between the EBML spec and the EBML Schema, but it makes the EBML Schema less dependent on the EBML spec. Also the old specdata.xml documented the EBML Header and Global Elements in addition to the Body.

**Comment by dericed** [comment]
ping @robUx4, opinion about this change?

**Comment by dericed** [comment]
ping to @robUx4 again. In your view should we say that all EBML Schema must include the EBML Header elements?

**Comment by robUx4** [comment]
`MUST document the of the EBML Header` there's a typo in there.
I agree with the general goal and implementation.

**Comment by retokromer** [comment]
I guess, it’s fine.

**Comment by robUx4** [comment]
As mentioned in https://github.com/Matroska-Org/matroska-specification/pull/135#issuecomment-307703820, do we want to force writing the whole EBML header definition for each format or only the differing values ?

**Comment by dericed** [comment]
Good point. OK I'll update the patch to reflect only storing the differences, i.e. constraints.

**Comment by dericed** [comment]
resolved by https://github.com/Matroska-Org/ebml-specification/pull/152
