### ISSUE TITLE
Schema links do not render in markdown

### ISSUE THREAD

**Issue by ablwr** [Matroska-Org/ebml-specification#146]
Links to XML Schema for EBML Schema and EBML Schema Example in specification.markdown do not render. How should these be corrected?

![screen shot 2017-05-17 at 20 29 52](https://cloud.githubusercontent.com/assets/3260492/26181622/a8eff32e-3b3f-11e7-987f-359573e54c3f.png)

**Comment by dericed** [comment]
It could be corrected by copy/pasting the contents of those files over the `<{{references}}`. There are some disadvantages to each way. For instance, if the xsd lives within the specification, it is harder to use as a schema in practice.

**Comment by ablwr** [comment]
copy/pasting the contents is better than what look like errors!

**Comment by ablwr** [comment]
Reading this again -- do you mean cut and pasting? Agreed, linking would be better. But why is this failing to link?

**Comment by dericed** [comment]
The linking syntax is [supported by mmark](https://github.com/miekg/mmark/wiki/Syntax#including-code-fragments), which is the utility which converts from markdown to rfc xml. But that syntax isn't natively supported in github rendered markdown.

**Comment by robUx4** [comment]
so no issue ?

**Comment by dericed** [comment]
Either we close the issue by:

1. Copy/paste the referenced xml into the markdown.
2. Determine that a fully representative and as-is markdown rendering is not a goal.

I prefer #2, to close the issue and perhaps add a warning to the readme that the markdown itself is not authoritative, but the rendered output of the makefile or better-yet the cellar document tracker is. @ablwr?

**Comment by ablwr** [comment]
Oh okay. Option 2 is fine with me!! Thought it was an error but now I see it's just because of the mediatory nature of the the beautiful github-flavored markdown.
