### ISSUE TITLE
how to convert date field from bytearray to date in javascript?

### ISSUE THREAD

**Issue by publicocean0** [Matroska-Org/ebml-specification#147]

**Comment by robUx4** [comment]
I don't think it's an actual issue but a JavaScript question which is more general. Either you know how to handle integers as they are in EBML and you can probably have something that convert to/from UNIX dates or something similar : https://stackoverflow.com/questions/847185/convert-a-unix-timestamp-to-time-in-javascript You just shift the EBML dates back to unix timestamps, Some EBML libraries do that.
Or you can't handle EBML integer values, which would be odd if you can handle EBML length.
