### ISSUE TITLE
Segmentation webml

### ISSUE THREAD

**Issue by publicocean0** [Matroska-Org/ebml-specification#153]
hi i need a little help , just a question:
i m realizing a demuxer formatting webm in mse stream.
Initialization segment is the same for all the sourcebuffer? the segment for track x contains just blocks of this track?

**Comment by publicocean0** [comment]
it seams i have to demux the stream

**Comment by ablwr** [comment]
All set?

**Comment by publicocean0** [comment]
It seams i have to realize a initialization segment for every track

**Comment by robUx4** [comment]
This does not seem relevant to this repository that only deals with EBML, the foundation on which Matroska is based on, on which WebM is based on.
I recommend looking for a public place to discuss WebM and adaptive streaming.
