### ISSUE TITLE
Why EBML?

### ISSUE THREAD

**Issue by retokromer** [Matroska-Org/ebml-specification#158]
Add scope to the abstract.

**Comment by dericed** [comment]
We already have the [Abstract](https://github.com/Matroska-Org/ebml-specification/blob/master/rfc_frontmatter.markdown) and the [Introduction](https://github.com/Matroska-Org/ebml-specification/blob/master/specification.markdown#introduction). Could you say more about what questions should be answered by a Scope section?

**Comment by retokromer** [comment]
This has been pointed out during the IETF 99 meeting. I opened the issue in order to not forget that for the next version.

**Comment by retokromer** [comment]
@dericed I’ve read this Abstract and compared it to others. In my opinion, there is no need for an amend. As I don’t know what the person missed during the meeting, I’m closing this issue. Sorry for the noise.

**Comment by robUx4** [comment]
Actually that's for the EBML repository. The idea was to explain why EBML is needed and why it was created: to be Matroska's underlying generic/flexible/not-too-verbose format.
