### ISSUE TITLE
Extending EBML

### ISSUE THREAD

**Issue by robUx4** [Matroska-Org/ebml-specification#182]
In the `EBML Header` section of the specs it says 

> The EBML Header MUST only contain EBML Elements that are defined as part of this document.

In my understanding it means we can never add new elements in a forward compatible way. Should we change this text to fix this ? Or that means there can never be enhancements to EBML without creating an incompatible format.

**Comment by dericed** [comment]
Perhaps we could be more specific such as:
> The EBML Header of an EBML Document that uses an `EBMLVersion` of `1` MUST only contain EBML Elements that are defined as part of this document.

This would say that new elements would require a version bump.

**Comment by robUx4** [comment]
Sounds good to me. PR ?
