### ISSUE TITLE
EBML element as Multiple?

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/ebml-specification#21]
Is this a bug? The EBML element is listed as "Multiple". Thus a file could use:

```
<EBML>
<Segment>
<EBML>
```
or
```
<EBML>
<EBML>
<EBML>
<Segment>
```

I can't see any reason this would be helpful. How do EBML parser handle cases with multiple EBML elements? For instance what if one EBML element says matroska version 1 and another EBML element says webm version 2.

I suggest that if EBML elements are listed as multiple, that there be some documentation to advise on how to interpret their potentially contradictory contents.

Another issue with this is that the definition of the EBML element says that the EBML document must start with an EBML element, but since multiple EBML elements are allowed, more EBML elements may be used elsewhere (the middle or tail). I noticed that in XML specs, their equivalent of the EBML element which is the XML Declaration is only allowed to occur at the beginning and may only occur once (see http://stackoverflow.com/questions/20251560/are-multiple-xml-declarations-in-a-document-well-formed-xml and its citations).

I propose removing the Multiple option for the EBML element.

**Comment by dericed** [comment]
OK, after thinking about it further I suppose a Matroska file could be an attachment of another Matroska file, thus there could be a valid reason for two EBML headers within one file. But....

**Comment by mbunkus** [comment]
»Multiple« does not refer to being used in the data portion of a binary element. If that were the case all data stored in binary elements that's simultaneously a valid ID in Matroska would have to be escaped somehow.

I think the reason why we allowed this was to enable binary concatenation of Matroska files (»cat file1.mkv file2.mkv > file3.mkv« and similar ways on Windows).

**Comment by dericed** [comment]
Can we consider the 'Yes' or 'No' of 'Multiple' with the EBML Template to be whether or not the element may occur multiple times within a parent Element? If so, then for the case of Level 0 elements (since there is no parent), can we say that if a Level 0 is multiple then the multiplicity refers to use of the Level 0 element within the `EBML Document` (rather than multiplicity within a file which could be an `EBML Stream`)? And if so, then can we change the `EBML Master-element` from yes to no (since the `EBML Master-element` infers to start of an `EBML Document`?

**Comment by mbunkus** [comment]
Yes to your questions (IMHO).
