### ISSUE TITLE
Remove some double quotes of defined names

### ISSUE THREAD

**Issue by robUx4** [Matroska-Org/ebml-specification#225]
At least the ones in upper case. Or maybe it's the backtick to RFC text translation that does that ?

As reported by Robert Sparks
https://mailarchive.ietf.org/arch/msg/cellar/gCFVwpnS79yZFsGk6yXucB5sMn0

**Comment by robUx4** [comment]
I can confirm it's the backticking that's causing the problem.

**Comment by robUx4** [comment]
Looks like `mmark` translates to backticks, either to `<spanx style="verb">` in v2 format or `<tt>` in v3 format (except the v3 format seems unusable by `xml2rfc`).

It seems that if we dial down the style to "emph" instead of "verb" it should be enough.
https://xml2rfc.tools.ietf.org/rfc7749.html#element.spanx

**Comment by robUx4** [comment]
So backticks are not the thing to use. It means Code Span: 
https://miek.nl/2016/march/05/mmark-syntax-document/#code-spans

What we should use it `_` or `*`. I think `_` is the most readable.
https://miek.nl/2016/march/05/mmark-syntax-document/#emphasis

**Comment by robUx4** [comment]
In the end using `_` it becomes a `_` in the text version. That's even less readable. So I think removing the backticks is the way forward.

**Comment by dericed** [comment]
IIRC one of the review comments was to backtick the first reference and unbacktick the subsequent references.

**Comment by robUx4** [comment]
We could keep the backticking in the ` 2. Notation and Conventions ` section. After all the RFC8174 text is also double quoted there. The separation of name and definition seems clearer that way.
