### ISSUE TITLE
line breaks

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/ebml-specification#35]
As discussed at VDD, I started this work with a hard 72 column line wrap, but if a 72 column output is needed this could be done as an output rather than maintained through all edits. Any objection if I remove the hard 72 column line wrap?

**Comment by mbunkus** [comment]
I'm not sure what you mean, exactly. If you mean you're going to make the lines as long as you want then I'm not all for it. If, however, you mean that when you change something and lines end up shorter you won't reformat the whole paragraph then I'm fine with that as it also cuts down on the diff making it easier to review.

**Comment by robUx4** [comment]
Definitely, if you want to add a word at the beginning and end up changing every other line, we lose visibility of the actual change.

**Comment by dericed** [comment]
fixed in https://github.com/Matroska-Org/ebml-specification/commit/a9e93e2d6ee168c60ee3ff26559485e8ec39328b
