### ISSUE TITLE
use of 'multiple' in element definitions

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/ebml-specification#38]
Void is not listed as 'multiple'. Also CRC is not multiple either but certainly multiple CRC are allowed in one EBML Document.

Is it right to consider that 'multiple' indicates whether the element may occurs more than once within its parent master-element (as opposed to multiple within the whole EBML Document)?

**Comment by robUx4** [comment]
Yes that's what it means.

Multiple CRC don't make much sense, maybe for safety but they should be on the same data and not included in these data.

Void should be marked as multiple. There's no reason to be able to only void one element and never another in the same parent.

**Comment by dericed** [comment]
Unfortunately there seem to be multiple divergent CRC definitions across the docs. In this repo the definition is:

> The CRC is computed on all the data from the last CRC element (or start of the upper level element), up to the CRC element, including other previous CRC elements. All level 1 elements SHOULD include a CRC-32.

But the same definition doesn't allow multiple. But the definition seems to indicate that multiple could be used in a master element and the crc value documents the data in between the crc elements. So:

```xml
<EBML>
  <CRC documenting EBMLversion and readverion only/>
  <EBMLVersion/>
  <EBMLReadVersion/>
  <CRC documenting DocTypeVersion and DocTypeReadVersion only/>
  <DocTypeVersion/>
  <DocTypeReadVersion/>
</EBML>
```

so either the 'multiple' of crc is wrong, or the definition is misleading.

**Comment by dericed** [comment]
Any votes on how to handle this conflict? Either the CRC element definition should change (since the defintion refers to multiple CRC in one master-element) or CRC should be set to multiple.

**Comment by mbunkus** [comment]
Allowing multiple CRC elements for improved error detection makes more or less sense to me. I highly doubt anyone will ever really use it, but we should allow it. Therefore I vode for changing the definition to allow multiple instances per master.

**Comment by dericed** [comment]
Closing this ticket. The definition of multiple and the use of CRC-32 Elements has been clarified in recent work.
