### ISSUE TITLE
The signature elements should be marked as deprecated

### ISSUE THREAD

**Issue by robUx4** [Matroska-Org/ebml-specification#4]
And maybe put in a separate paragraph. Even if marking the code in CSS is possible it would be better not to rely on that, since an RFC will not have such features anyway.

**Comment by dericed** [comment]
I think this issue may have been resolved by moving the signature section to a separate document with the status statement added, as done here: https://github.com/Matroska-Org/ebml-specification/commit/3596370868f65a0fbec9e51f3956fc63626858f2. I suggest closing this issue.

**Comment by mbunkus** [comment]
Sounds reasonable.
