### ISSUE TITLE
matroska as default docType?

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/ebml-specification#74]
Up until https://github.com/Matroska-Org/ebml-specification/commit/3304085e3650e339b961404624983af772ea31d5, there was no default for docType in the EBML Schema. So the docType Element was required to be stored according to the EBML specification. The referenced patch was done to resolve a perceived discrepancy between the EBML and Matroska specs since the EBML did not define a default for docType, but the Matroska spec did define a docType default (matroska).

At the time it was deemed that the Matroska spec was correct partly because it had been historically better maintained than the EBML spec.

However, I noted that the Matroska version of that on https://matroska.org/technical/specs/index.html is followed by a statement:

    The default values defined for the EBML header correspond to the values for a Matroska stream/file.
    When parsing the EBML header the default values are different, irrespective of the DocType defined.

Because of this statement, I think that the discrepancy between was intentional. That EBML's definition of docType is relevant to any EBML, ie docType MUST be stored since it is mandatory with no default. And in the Matroska spec matroska was listed as the default because a Matroska file must semantically understand 'matroska' is the docType.

I propose reverting https://github.com/Matroska-Org/ebml-specification/commit/3304085e3650e339b961404624983af772ea31d5, so that a generical EBML Document MUST store docType whether Matroska or not. And, in the Matroska spec, it should note that for the case of Matroska the docType MUST be 'matroska'. This would change the current implication that docType does not necessarily need to be stored if the docType is matroska.

cc @robUx4 @mbunkus

**Comment by retokromer** [comment]
>I propose reverting 3304085, so that a generical EBML Document MUST store docType whether Matroska or not. And, in the Matroska spec, it should note that for the case of Matroska the docType MUST be 'matroska'. This would change the current implication that docType does not necessarily need to be stored if the docType is matroska.

Good catch! I my opinion, this is the right way to go.

**Comment by mbunkus** [comment]
Echoing Reto: good catch. I concur.
