### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by retokromer** [Matroska-Org/ebml-specification#77]
In section **Element Name: Signature** something is missing:

`Description:    The signature of the data (until a new.`

at least ")" but perhaps more, as I cannot understand.

**Comment by mbunkus** [comment]
Probably something like "until a new signature element is found". Anyway, this is one of the deprecated and never used elements that @robUx4 has already suggested we remove. Therefore I'll leave this open until we decided whether or not to remove those deprecated elements now.
