### ISSUE TITLE
define EBML Reader & Writer and define its expected behavior

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/ebml-specification#88]
Based on [Tim's comment](https://mailarchive.ietf.org/arch/msg/cellar/Mfj44tK1gyfqjU3Uu1tI5fMovtk):

> A number of the things listed as "attacks" are simply things you said someone writing an EBML Document MUST NOT do (or not doing things you said they MUST do). But in none of those cases do you say what is expected of someone reading a document containing these attacks.

@mbunkus, @robUx4, ideas for such a section? There is a bit of similar language at https://github.com/Matroska-Org/matroska-test-files/blob/master/readme.md but I don't think we have such language for EBML Readers yet.

**Comment by dericed** [comment]
This section should note what an EBML Reader should do when encountering an invalid VINT_WIDTH. For instance if a Master Element contains 0b0000000000000000.

**Comment by dericed** [comment]
also from Tim's review: 
> What are you supposed to do if attempting to read a length (e.g., of a String, which has no defined maximum length) and the entire rest of the file consists of zero bytes?

**Comment by dericed** [comment]
Should also define what to do with invalid Element IDs. For instance if the Element Data of a Master Element starts with 0x11111111, this is an invalid Element ID, what should the reader do? The next octet(s) could depict an Element Data Size so that it could be known how much to skip but with an invalid Element ID, I wouldn't trust the next data to be a VINT of Element Data Size.

**Comment by dericed** [comment]
Also what should an EBML Reader do if encountering an Element with unknown size when it is not permitted, such as with a string or integer?

**Comment by dericed** [comment]
Should define behavior for EBML Reader with excessive lengths of strings. For instance a string element in Matroska may have a length of ~72 Petabytes. Perhaps it is unreasonable to expect that the EBML Reader handle this appropriately.

**Comment by dericed** [comment]
As Tim wrote regarding "A String Element may declare any length from zero to 'VINTMAX'."
> MAY? VINTMAX is not a single value. Its value depends on the octet width (length?) of the Element Data Size. Is there any restriction on this octet width? If not, I would just phrase this as, "A String Element can have any length, including zero." However, it is obvious that no implementation will be able to support strings of completely arbitrarily length. Is there some required minimum that decoders are required to handle? When is a 32-bit system with no more than 4 GB of RAM justified in rejecting a string as too large? How about an embedded media player in someone's television? How would someone writing an EBML document know when writing a string if all decoders will be able to handle it?

**Comment by dericed** [comment]
What should an EBML Reader do when encountering a character outside of the permitted ASCII range in a string element?

**Comment by dericed** [comment]
As Tim wrote regarding "A String Element may declare any length from zero to 'VINTMAX'."
> MAY? VINTMAX is not a single value. Its value depends on the octet width (length?) of the Element Data Size. Is there any restriction on this octet width? If not, I would just phrase this as, "A String Element can have any length, including zero." However, it is obvious that no implementation will be able to support strings of completely arbitrarily length. Is there some required minimum that decoders are required to handle? When is a 32-bit system with no more than 4 GB of RAM justified in rejecting a string as too large? How about an embedded media player in someone's television? How would someone writing an EBML document know when writing a string if all decoders will be able to handle it?

**Comment by dericed** [comment]
Re: "All EBML Elements within the EBML Header MUST NOT utilize any Element ID with a length greater than 4 octets.  All EBML Elements within the EBML Header MUST NOT utilize any Element Data Size with a length greater than 4 octets."

Tim asks:
> What is a decoder supposed to do if these restrictions are violated?

**Comment by dericed** [comment]
What should the EBML Reader do if an Element does not contain the required Child Elements (Child Elements have minOccurs that is not met)?

**Comment by dericed** [comment]
What should EBML Reader do if there are Child Elements that occur more than maxOccurs allows?

**Comment by retokromer** [comment]
The easiest (for the parser) is to ignore from `maxOccurs` on.

**Comment by robUx4** [comment]
So many questions

**Comment by robUx4** [comment]
In fact I'm not sure we have specified this but it should probably be written somewhere: when an invalid EBML element is detected (impossible EBML data size, EBML ID/size not matching the constraints from the EBML header, etc) the first octet should be discarded and the next octet should be used as the start of the next EBML element. It stops looking for octets when the end of the parent EBML element is reached. This is how libebml(1|2) has always worked.

It may be too implement specific though. Other forms or error recovery may occur that would find EBML elements in other more valid places.
