### ISSUE TITLE
move definitions of attributes, data types, and elements from tables to sections 

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/ebml-specification#89]
The current tables make it hard to use cross-references and forward references within the document. I propose reforming these three sections to use nested headers instead of tables.

Once added include forward references for terms and concepts used in the document before they are explained. Such as forward references to EBMLMaxIDLength, EBMLMaxSizeLength, EBML Data Type, unknownsizeallowed, level.

See suggestions for forward references in https://mailarchive.ietf.org/arch/msg/cellar/Mfj44tK1gyfqjU3Uu1tI5fMovtk.

**Comment by dericed** [comment]
note to self to forward reference 'level'

**Comment by dericed** [comment]
Noting that [RFC7749](https://tools.ietf.org/html/rfc7749) is a good example of defining xml-like data structures in RFC form.

**Comment by mbunkus** [comment]
That RFC looks very good to me. I'm in favor of reworking our document this way.
