### ISSUE TITLE
why are Element IDs with all 0 or all 1 in VINT_DATA reserved?

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/ebml-specification#90]
On the [CELLAR list](https://mailarchive.ietf.org/arch/msg/cellar/Mfj44tK1gyfqjU3Uu1tI5fMovtk) Tim asked:

> What is an implementation supposed to do if it encounters a file that violates this restriction? What is the purpose of reserving the various all-ones Element IDs? Or the zero Element ID, for that matter?

which regards the current line in the spec:

> "The VINT_DATA component of the Element ID MUST NOT be set to either all zero values or all one values."

I don't know the answer to this. @robUx4, @mbunkus, do you know the answer to the questions above?

**Comment by mbunkus** [comment]
The easier case is all bits set to 0. This means that the first byte of a potential ID is 0x00, which in turn means that there's no `VINT_MARKER` present. It violates that `MUST` in the definition of `VINT_MARKER`.

Now we're back in "junk" territory. I'm very reluctant to allow consumers to reject files with such invalid data, just as I've said in #92. How do other file formats handle this?

About all bits set to 1: I don't remember why we've disallowed this. I'd say to treat it the same as 0x00, whatever we decide to do with that.

**Comment by dericed** [comment]
> The easier case is all bits set to 0. This means that the first byte of a potential ID is 0x00, which in turn means that there's no `VINT_MARKER` present. It violates that `MUST ` in the definition of `VINT_MARKER`.

No the issue is all 0 as VINT_DATA, such as an Element ID of 0x80, which is currently invalid.

**Comment by dericed** [comment]
Also the first byte of a potential ID is allowed to be 0x00 if the EBMLMaxIDLength is greater than 8.

**Comment by robUx4** [comment]
I'm not sure EBMLMaxIDLength above 8 bytes should be allowed. That makes parsing EBML data a lot more hazardous. 8 bytes ought to be enough for anybody ;)

**Comment by robUx4** [comment]
Historically the boundary values have been reserved in case we need to extend things in an unexpected way. Luckily we never had to use any of these boundary values. The all zero value could have certainly be used for Void.

I really don't know if it's better to mark them as reserved (valid but no meaning yet) or invalid (data are assumed corrupted there).

**Comment by mbunkus** [comment]
I'd prefer reserved.
