### ISSUE TITLE
draft XML Schema for EBML Schemas

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/ebml-specification#91]
I think having an XML Schema as a machine-readable document to verify that an EBML Schema (which is an XML Document) is correctly formed.

**Comment by dericed** [comment]
can do, but https://github.com/Matroska-Org/ebml-specification/pull/83 should be finalized first.

**Comment by retokromer** [comment]
I agree on both: https://github.com/Matroska-Org/ebml-specification/pull/83 first and then XML Schema to verify EBML Schema.

**Comment by dericed** [comment]
An `XML Schema` of an `EBML Schema` is very meta.

**Comment by robUx4** [comment]
Fixed by https://github.com/Matroska-Org/ebml-specification/pull/115
