### ISSUE TITLE
consider EBNF for range expressions

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/ebml-specification#96]
For example the description of float ranges is very complex:
> Within an expression of a float range, as in an integer range, the `-` (hyphen) character is the separator between the minimal and maximum value permitted by the range. Hexadecimal Floating-Point Constants also use a `-` (hyphen) when indicating a negative binary power. Within a float range, when a `-` (hyphen) is immediately preceded by a letter `p`, then the `-` (hyphen) is a part of the Hexadecimal Floating-Point Constant which notes negative binary power. Within a float range, when a `-` (hyphen) is not immediately preceded by a letter `p`, then the `-` (hyphen) represents the separator between the minimal and maximum value permitted by the range.

Perhaps we should consider [EBNF](https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_Form) for these expressions.

**Comment by retokromer** [comment]
I am a big fan of EBNF since... ever! More precisely, since 1977 when a read Kathleen Jensen and Niklaus Wirth's Pascal definition and wrote my first compiler for the Z80 CPU using that definition.

Yet don't forget to add:
```
<empty statement> ::= <empty>
<empty> ::= 
```
(sorry, I couldn't resist ;-)

**Comment by mbunkus** [comment]
I'm definitely fine with EBNF, too. In fact I'm strongly in favor of using it :) People are used to reading EBNF, it's well-established.

**Comment by robUx4** [comment]
You probably want to use [RFC 4234](https://tools.ietf.org/html/rfc4234) directly. They have their own hexadecimal definition. They don't have a floating point representation ready to use though.

**Comment by dericed** [comment]
I'm not familiar enough with EBNF to draft a pull request. Any volunteer?

**Comment by mbunkus** [comment]
I can read EBNF, but I've never written it before…

**Comment by robUx4** [comment]
Not an issue anymore, it's been done and merged using the RFC format.
https://github.com/Matroska-Org/ebml-specification/pull/106
