### ISSUE TITLE
define max value for EBMLMaxIDLength & EBMLMaxSizeLength

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/ebml-specification#98]
I suggest that these need a max value. A value of 7,625,597,484,987 for EBMLMaxIDLength is allowed but not sane to expect that an EBML Reader should prepare for it.

**Comment by mbunkus** [comment]
I'm hesitant to enforce maximums here. I mean… what if someone wants to use really long IDs for error resilience purposes (making it easier to differentiate between an ID and content when a consumer is re-syncing after running into junk)?

I'd be fine with a large maximum, though. Maybe… I don't know… 1024 for `EBMLMaxIDLength`. That's probably as arbitrary as other values.

Additionally, what purpose would imposed maximums serve? To protect consumers? Well, there are consumers on very different hardware; what protects a high-end machine wouldn't protect a low-end one. And a limit that protects low-end machines might be overly restrictive for purposes where access on arbitrary hardware isn't required.

**Comment by dericed** [comment]
EBML without a DocType is meaningless, so perhaps a better way to answer this issue is to state that DocType definitions (i.e. webm, matroska, etc) MUST define max values for EBMLMaxIDLength & EBMLMaxSizeLength

**Comment by robUx4** [comment]
IMO a max value of 8 for each is desirable. That's a good assumption to rely on when building an EBML parser. On the other hand if we don't, that means probably all current EBML parsers are not compliant, for no real gain. If someone really need more IDs they should not use EBML.

**Comment by robUx4** [comment]
Also we don't know how to define/use elements with a length above 8 bytes.

The original intent was to allow formats to use smaller size when they don't need more. Some elaborate parsers may use less memory in that case. Or parsers designed for that particular format may detect when they can't handle other larger EBML formats.

**Comment by dericed** [comment]
I suppose we could recommend that the EBML Document Type define these limits (as Matroska already does) so that the scenario @mbunkus mentions is still possible (designing an extreme ID length for increased resilience).

This reminds me of another issue. The EBML Schema section says:
> The `EBML Schema` does not itself document the `EBML Header`, but documents all data of the `EBML Document` that follows the `EBML Header`.

but in Matroska we have cases where Matroska defines further constraints on EBML Header Elements. For example, EBML allows EBMLMaxSizeLength=9 but Matroska doesn't.

Should the `EBML Schema` include the `EBML Header` with the allowance of additional constraints? We could say that the `EBML Header` elements must be included with an `EBML Schema` and that all `EBML Headers` of that DocType must be valid to the `EBML Header` elements of the EBML definition. In other words, the EBML spec allows EBML Headers that may not be valid within the `Document Type`'s `EBML Schema` (ie `EBMLMaxSizeLength=9`) but the `Document Type`'s `EBML Schema` MUST define an `EBML Header` that is valid to the EBML spec.

**Comment by robUx4** [comment]
@dericed I suggest you open a separate Issue/thread for these Schema restrictions.

As for this particular thread, I think there's no need in EBML to impose maximums after all. Each specific format can have its own set of extra rules on the other hand it makes generic EBML parsing a lot more difficult though as they should be able to handle millions size IDs/Sizes. Maybe such tools can just say the file may be valid but they have no way to know... For Matroska we definitely want to force maximum values.

**Comment by dericed** [comment]
agreed. I'm closing this issue and starting a new one based on the last few comments.
